// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jnihwbiozhlatjlycfon.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpuaWh3YmlvemhsYXRqbHljZm9uIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk2NTg1OTAsImV4cCI6MjA2NTIzNDU5MH0.cmfy1cokxEna9DCXTM_kjRxtXIp9MjxSx6YEHOiLcM4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);